### ISSUE TITLE
Obok DeDrM plugin not working in Calibre 6.17.0?

### ISSUE THREAD

**Issue by ZenmasterJ** [noDRM/DeDRM_tools#327]
### Question / bug report

My OBOK plugin is installed successfully from the latest DeDRM release (10.0.3). The icon is on the top of my calibre screen.

When I press the icon, I get the following error message.

calibre, version 6.17.0
ERROR: Unhandled exception: <b>AttributeError</b>:type object 'QTableWidgetItem' has no attribute 'UserType'

calibre 6.17  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Set KFX metadata (from KFX Output) (1, 67, 0) && KFX Output (1, 67, 0) && KePub Input (3, 6, 3) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 6, 3) && Kobo Utilities (2, 16, 6) && KoboTouchExtended (3, 6, 3) && Obok DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 135, in launchObok
  File "calibre_plugins.obok_dedrm.dialogs", line 102, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 154, in populate_table
  File "calibre_plugins.obok_dedrm.dialogs", line 179, in populate_table_row
  File "calibre_plugins.obok_dedrm.dialogs", line 439, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 412, in __init__
AttributeError: type object 'QTableWidgetItem' has no attribute 'UserType'

Running Windows 10.
I am trying to open books downloaded to my Kobo App for PC. 
I can add the books by putting a .kepub at the end of the generic file name from the Kobo app folder, but cannot open them (Calibre says they contain DeDRM).
I know that I need the Obok plugin to deDRM these files, but when I click on the Obok plugin icon in calibre, I get the above error message. Got the same error message in Calibre 6.08 as well before I just updated Calibre to 6.17.

### Which version of Calibre are you running?

6.17

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
Log shows that you still have 7.2.1 plugins.  For calibre 6, you need 10.0.3.

**Comment by ZenmasterJ** [comment]
I have installed the obok plugin from the DeDRM 10.03 package. In Calibre, from the Preferences tab, I go to Advanced then Load Plugin from File, and then choose the OBOK zip file in the DeDRM 10.03 package. That OBOK plugin still reads as v 7.2.1. How can I download the 10.03 OBOK plugin?

**Comment by ElleKayEm** [comment]
Make sure you are really browsing to the correct folder for 10.0.3 and restart calibre after loading it.

**Comment by calyst1978** [comment]
I'm hoping I can jump on this thread, as I'm having a similar issue. I have books purchased via Kobo that I would like to manage in Calibre. I just installed Obok DeDRM v 10.0.3. I added the Kobo serial number and the path to the Kobo Desktop App downloads.

If I run Obok in Calibre with the Kobo connected, it appears to see (only) the books that are on the device. However, trying to add a book from that list gives me "[title] not added because it couldn't be decrypted." 

If I disconnect the device and run Obok again, I get the message below. I have five books in the folder at the path I defined when configuring Obok. I left one without a file extension, added .epub to one, and added .kepub to the other three.
> calibre, version 6.19.1
> ERROR: Obok DeDRM v10.0.3: <p>Could not find Kobo Library
> <p>Windows/Mac: do you have Kobo Desktop installed?
> <p>Windows/Mac/Linux: In case you have an Kobo eInk device, connect the device.

Obok also doesn't appear to run against books that I pull into Calibre manually:

If I drag and drop an .epub version into Calibre, it shows some of the metadata and I can open it, but isn't readable.

If I drag and drop a .kepub version into Calibre, I get the following when I try to open it:
> calibre, version 6.19.1
> ERROR: Loading book failed: Failed to open the book at C:\Users\calys\Calibre Library\Unknown\0317d0c1-33bb-4ae0-a785-85d94edd652 (379)\0317d0c1-33bb-4ae0-a785-85d94ed - Unknown.kepub. Click "Show details" for more info.
> 
> Failed to convert book: C:\Users\calys\Calibre Library\Unknown\0317d0c1-33bb-4ae0-a785-85d94edd652 (379)\0317d0c1-33bb-4ae0-a785-85d94ed - Unknown.kepub with error:
> Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
> Traceback (most recent call last):
>   File "runpy.py", line 196, in _run_module_as_main
>   File "runpy.py", line 86, in _run_code
>   File "site.py", line 83, in <module>
>   File "site.py", line 78, in main
>   File "site.py", line 50, in run_entry_point
>   File "calibre\utils\ipc\worker.py", line 196, in main
>   File "<string>", line 1, in <module>
>   File "calibre\srv\render_book.py", line 826, in viewer_main
>   File "calibre\srv\render_book.py", line 817, in render_for_viewer
>   File "calibre\srv\render_book.py", line 794, in render
>   File "calibre\ebooks\oeb\iterator\book.py", line 53, in extract_book
>   File "calibre\ebooks\conversion\plumber.py", line 755, in __init__
> ValueError: No plugin to handle input format: kepub

Any recommendations? I appreciate your help!

**Comment by ElleKayEm** [comment]
For Obok, you only use Obok to import the books.  Alternatively, you can download the Adobe DRM versions from the Kobo website using ADE and then use the DeDRM plugin.

**Comment by calyst1978** [comment]
Okay, but the import isn't working, unless I'm doing it wrong. The first two examples I gave would have been using Obok to import, wouldn't they?

**Comment by ElleKayEm** [comment]
I've never had to configure anything when using Obok.  It just works with either my Kobo ereader or Kobo Desktop.  I seen others sometimes have issues like yours though.  I don't know what the trick is.
